name: update topios100 daily

on:
  workflow_dispatch:  # Trigger manually
  schedule:
    - cron: "00 12 * * *"

jobs:
  scrape-app-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Ensure your required version is used

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx google-play-scraper aiohttp aiohttp_socks DataRecorder pandas DrissionPage python-dotenv app_store_scraper requests tqdm

      - name: Run scraper and save results
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_D1_DATABASE_ID: ${{ secrets.D1_APP_DATABASE_ID }}    
          RESULT_FOLDER: ./result  # Adjust if necessary
          OUTPUT_FOLDER: ./output
        run: |
          python get-top100-app-daily.py

      # 新增：提交 date.txt 到仓库
      - name: Commit and push date.txt
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull origin ${{ github.ref_name }}
          mv date.txt ./date.txt
          git add date.txt
          git commit -m "chore: update date.txt [auto commit]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload files          
        uses: actions/upload-artifact@v4
        with:
            name: healthapps
            path: ./result/ # or path/to/artifact
